<a href="https://colab.research.google.com/github/yashar1908/Star-Classification/blob/main/Star_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('star_data.csv')

In [4]:
df.head()

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0             3068          0.002400        0.1700                   16.12   
1             3042          0.000500        0.1542                   16.60   
2             2600          0.000300        0.1020                   18.70   
3             2800          0.000200        0.1600                   16.65   
4             1939          0.000138        0.1030                   20.06   

   Star type Star color Spectral Class  
0          0        Red              M  
1          0        Red              M  
2          0        Red              M  
3          0        Red              M  
4          0        Red              M

In [10]:
X = df.iloc[:, :-3].join(df.iloc[:,-2:])

In [15]:
X.head()

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0             3068          0.002400        0.1700                   16.12   
1             3042          0.000500        0.1542                   16.60   
2             2600          0.000300        0.1020                   18.70   
3             2800          0.000200        0.1600                   16.65   
4             1939          0.000138        0.1030                   20.06   

  Star color Spectral Class  
0        Red              M  
1        Red              M  
2        Red              M  
3        Red              M  
4        Red              M

In [14]:
Y = df.iloc[:,-3]
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Star type, dtype: int64

In [16]:
X.describe()

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)
count       240.000000        240.000000    240.000000              240.000000
mean      10497.462500     107188.361635    237.157781                4.382396
std        9552.425037     179432.244940    517.155763               10.532512
min        1939.000000          0.000080      0.008400              -11.920000
25%        3344.250000          0.000865      0.102750               -6.232500
50%        5776.000000          0.070500      0.762500                8.313000
75%       15055.500000     198050.000000     42.750000               13.697500
max       40000.000000     849420.000000   1948.500000               20.060000

In [17]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Temperature (K)         240 non-null    int64  
 1   Luminosity(L/Lo)        240 non-null    float64
 2   Radius(R/Ro)            240 non-null    float64
 3   Absolute magnitude(Mv)  240 non-null    float64
 4   Star color              240 non-null    object 
 5   Spectral Class          240 non-null    object 
dtypes: float64(3), int64(1), object(2)
memory usage: 11.4+ KB


In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [21]:
y_test.shape

(48,)

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_train['Star color enc'] = le.fit_transform(X_train['Star color'])

In [34]:
X_train['Spectral Class enc'] = le.fit_transform(X_train['Spectral Class'])

In [31]:
X_train = X_train.drop('Star color', axis = 1)

In [35]:
X_train = X_train.drop('Spectral Class', axis = 1)

In [36]:
X_train.head()

Temperature (K)  Luminosity(L/Lo)  Radius(R/Ro)  Absolute magnitude(Mv)  \
0               3068          0.002400       0.17000                   16.12   
174             3600     240000.000000    1190.00000                   -7.89   
73              3150          0.008800       0.35000                   11.94   
183             3218          0.000452       0.09870                   17.34   
148             7723          0.000140       0.00878                   14.81   

     Star color enc  Spectral Class enc  
0                 8                   4  
174               8                   4  
73                8                   4  
183               8                   4  
148               9                   0

In [37]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
knn_model = KNeighborsClassifier(n_neighbors=6)
knn_model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [47]:
knn_model_2 = KNeighborsClassifier(n_neighbors=5)
knn_model_2.fit(X_train, y_train)

KNeighborsClassifier()

In [42]:
X_test['Star color enc'] = le.fit_transform(X_test['Star color'])
X_test['Spectral Class enc'] = le.fit_transform(X_test['Spectral Class'])
X_test = X_test.drop('Star color', axis = 1)
X_test = X_test.drop('Spectral Class', axis = 1)

In [43]:
y_pred = knn_model.predict(X_test)

In [45]:
accuracy = accuracy_score(y_test, y_pred)

In [46]:
accuracy

0.6041666666666666

In [49]:
y_pred_2 = knn_model_2.predict(X_test)

In [50]:
accuracy_2 = accuracy_score(y_test, y_pred_2)

In [51]:
accuracy_2

0.6458333333333334

In [72]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=6, random_state=1)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=6, random_state=1)

In [73]:
y_pred_rf = rf_classifier.predict(X_test)

In [74]:
accuracy_rf = accuracy_score(y_test, y_pred_rf)

In [75]:
accuracy_rf

1.0

In [76]:
from sklearn.metrics import classification_report, confusion_matrix
report_rf = classification_report(y_test, y_pred_rf)

In [77]:
print(report_rf)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         5
           2       1.00      1.00      1.00         8
           3       1.00      1.00      1.00        13
           4       1.00      1.00      1.00         6
           5       1.00      1.00      1.00        10

    accuracy                           1.00        48
   macro avg       1.00      1.00      1.00        48
weighted avg       1.00      1.00      1.00        48



In [79]:
cf = confusion_matrix(y_test, y_pred_rf)
print(cf)

[[ 6  0  0  0  0  0]
 [ 0  5  0  0  0  0]
 [ 0  0  8  0  0  0]
 [ 0  0  0 13  0  0]
 [ 0  0  0  0  6  0]
 [ 0  0  0  0  0 10]]
